thundersdata-frontend/td-design

packages/utils/src/index.ts, packages/utils/src/request/index.ts
=> fix: 导出request、添加快速引用

packages/utils/src/array/index.test.ts, packages/utils/src/json/index.test.ts, packages/utils/src/regex/index.test.ts, packages/utils/src/regex/index.ts, packages/utils/src/string/index.ts, packages/utils/src/url/index.ts
1、array/json/regex测试添加；
2、添加文本复制与文件下载功能。
=> fix: 补充utils中的测试，新增部分功能

package-lock.json, packages/web/components/login-form/index.tsx, packages/web/components/register-form/index.tsx, packages/web/components/reset-form/index.tsx, packages/web/components/sms-form/index.tsx, packages/web/package-lock.json, yarn.lock
=> feat: 按钮增加loading状态

packages/charts/src/components/auto-verticalroll/index.tsx, packages/charts/src/components/auto-verticalroll/style/index.less, packages/charts/src/components/auto-verticalroll/style/index.tsx, packages/charts/src/components/custom-table/index.tsx, packages/charts/src/components/custom-table/style/index.less, packages/charts/src/components/custom-table/style/index.tsx, packages/charts/src/components/icons-percentage/index.tsx, packages/charts/src/components/icons-score-chart/index.tsx, packages/charts/src/components/index.tsx, packages/charts/src/utils/raf/index.ts
1 iconsChart加入label,qutao提供自定义 
2 加入customTable和AutoVerticalRoll自动滚动组件
=> feat: 优化iconsChart及加入滚动table组件

packages/charts/package.json, packages/charts/yarn.lock
更新 g2plot 版本,新增 interactions 放大滑动条(zoom)等
=> fix: 更新 g2plot 版本

packages/react-native/components/config/theme.ts, packages/react-native/components/flex/FlexItem.tsx, packages/react-native/components/flex/index.tsx, packages/react-native/components/index.ts, packages/react-native/components/white-space/index.tsx, packages/react-native/components/wing-blank/index.tsx, packages/react-native/example/src/App.tsx, packages/react-native/example/src/theme.ts
1. 导出Spacing类型
2. 补充项目中自定义主题效果
=> feat: 新增Flex/WhiteSpace/WingBlank三个组件

packages/react-native/components/accordion/Panel.tsx, packages/react-native/components/accordion/index.tsx, packages/react-native/components/action-sheet/index.tsx, packages/react-native/components/config/theme.ts, packages/react-native/components/date-picker/index.tsx, packages/react-native/components/date-picker/type.d.ts, packages/react-native/components/index.ts, packages/react-native/components/picker/index.tsx, packages/react-native/components/picker/type.d.ts, packages/react-native/example/src/ActionSheetDemo.tsx, packages/react-native/example/src/App.tsx
=> feat: 完成ActionSheet组件

packages/react-native/components/config/theme.ts, packages/react-native/components/date-picker/index.tsx, packages/react-native/components/date-picker/type.d.ts, packages/react-native/example/src/App.tsx, packages/react-native/example/src/ModalDatePickerDemo.tsx
1.修复modal背景色问题
2.为datepicker组件增加format功能
ISSUES CLOSED: #101
=> fix: 修复modal背景色问题

packages/react-native/components/accordion/Panel.tsx, packages/react-native/components/accordion/index.tsx, packages/react-native/components/action-sheet/index.tsx, packages/react-native/components/badge/index.tsx, packages/react-native/components/card/index.tsx, packages/react-native/components/date-picker/index.tsx, packages/react-native/components/input/InputItem.tsx, packages/react-native/components/input/TextArea.tsx, packages/react-native/components/input/index.tsx, packages/react-native/components/picker/Cascader.tsx, packages/react-native/components/picker/NormalPicker.tsx, packages/react-native/example/.gitignore, packages/react-native/example/ios/Podfile.lock, packages/react-native/example/src/App.tsx, packages/react-native/example/src/InputDemo.tsx
全局替换StyleSheet.hairlineWidth
修复hooks依赖报错问题
ISSUES CLOSED: #118
=> fix: 修复Input组件在安卓上输入文字被遮挡的问题

packages/react-native/example/src/common.tsx, packages/react-native/example/src/screens/Homepage.tsx, packages/react-native/example/src/screens/TextDemo.tsx, packages/react-native/example/src/stacks/mainStack.tsx, packages/react-native/src/box/index.md, packages/react-native/src/text/index.md
=> feat: 补充Text组件文档

packages/react-native/example/src/screens/NoticeBarDemo.tsx, packages/react-native/src/notice-bar/HorizontalNotice.tsx, packages/react-native/src/notice-bar/index.md, packages/react-native/src/notice-bar/index.tsx
=> feat: 补充NoticeBar组件文档

packages/react-native/example/src/screens/ModalDatePickerDemo.tsx, packages/react-native/src/date-picker/DatePicker.android.tsx, packages/react-native/src/date-picker/DatePicker.ios.tsx, packages/react-native/src/date-picker/index.md, packages/react-native/src/date-picker/index.tsx, packages/react-native/src/date-picker/type.ts
1. 调整DatePicker各列的布局
2. 修复DatePicker在View模式下没有获取值的方法
3. 删除多余的一些类型
=> feat: 为DatePicker组件补充文档

packages/react-native/example/src/screens/InputDemo.tsx, packages/react-native/src/auto-complete/index.tsx, packages/react-native/src/input/InputItem.tsx, packages/react-native/src/input/TextArea.tsx, packages/react-native/src/input/index.md, packages/react-native/src/input/index.tsx
补充一些缺失的属性
优化TextArea组件的字数限制展示格式
=> feat: 为Input组件补充文档

packages/react-native/src/picker/Cascader.tsx, packages/react-native/src/picker/NormalPicker.tsx, packages/react-native/src/picker/index.md, packages/react-native/src/picker/index.tsx, packages/react-native/src/picker/type.ts
修复picker组件在页面内展示时无法获取到value的问题
=> feat: 为Picker组件新增文档

packages/react-native/example/src/screens/CollapseTextDemo.tsx, packages/react-native/src/collapse-text/index.md, packages/react-native/src/collapse-text/index.tsx
=> feat: 为CollapseText组件补充文档

packages/react-native/src/float-button/index.md, packages/react-native/src/float-button/index.tsx, packages/react-native/src/float-button/type.ts
=> feat: 为FloatButton补充文档

packages/react-native/example/src/screens/CollapseTextDemo.tsx, packages/react-native/example/src/stacks/mainStack.tsx, packages/react-native/src/collapse-text/index.tsx
=> fix: 修复CollapseText组件在安卓上的bug

packages/react-native/example/src/screens/ModalConfirmDemo.tsx, packages/react-native/example/src/screens/ModalPromptDemo.tsx, packages/react-native/example/src/stacks/mainStack.tsx, packages/react-native/src/date-picker/index.tsx, packages/react-native/src/modal/alert/AlertContainer.tsx, packages/react-native/src/modal/confirm/ConfirmContainer.tsx, packages/react-native/src/modal/confirm/index.tsx, packages/react-native/src/modal/index.md, packages/react-native/src/modal/index.tsx, packages/react-native/src/modal/type.ts, packages/react-native/src/picker/Cascader.tsx, packages/react-native/src/picker/NormalPicker.tsx
1.新增Modal.confirm方法
2.修改Modal.alert方法
=> docs: 增加Modal组件文档

packages/react-native/src/image-header/AnimateHeader.tsx
=> fix: 修复ImageHeader组件下拉也出现Header的问题

packages/charts/README.md, packages/charts/package.json, packages/charts/src/baseUtils/chart/index.ts, packages/charts/src/components/chart-dom/index.tsx, packages/charts/src/components/chart-plot/index.tsx, packages/charts/src/components/com-block/style/index.less, packages/charts/src/config.ts, packages/charts/src/g2components/CustomDonutRose/index.ts, packages/charts/src/g2components/base.ts, packages/charts/src/utils/create-column-line-plot/index.ts, packages/charts/src/utils/create-donut-plot/index.ts, packages/charts/src/utils/create-group-column-plot/index.ts, packages/charts/src/utils/create-grouped-column-line-plot/index.ts, packages/charts/src/utils/create-line-plot/index.ts, packages/charts/src/utils/create-liquid-plot/index.ts, packages/charts/src/utils/create-radial-stack-plot/index.ts, packages/charts/src/utils/create-scatter-plot/index.ts, packages/charts/src/utils/create-stack-area-plot/index.ts, packages/charts/src/utils/create-stack-column-plot/index.ts, packages/charts/src/utils/create-stack-rose-plot/index.ts, packages/charts/src/utils/create-waterfall-plot/index.ts
=> 完成 g2plot v2 升级，最后一版发布

package.json, packages/lego/example/VideoDemo/demo2.tsx, packages/lego/example/VideoDemo/demo3.tsx, packages/lego/example/VideoDemo/demo4.tsx, packages/lego/example/VideoDemo/demo5.tsx, packages/lego/example/VideoDemo/demo6.tsx, packages/lego/example/VideoDemo/demo7.tsx, packages/lego/example/VideoDemo/demo8.tsx, packages/lego/package.json, packages/lego/src/other/Video/index.md, packages/lego/src/other/Video/index.tsx
=> fix: 替换视频组件

packages/react-native/example/src/screens/NumberKeyboardDemo.tsx, packages/react-native/package.json, packages/react-native/src/number-keyboard/NumberKeyboardFilter.tsx, packages/react-native/src/number-keyboard/NumberKeyboardInput.tsx, packages/react-native/src/number-keyboard/index.md, packages/react-native/src/number-keyboard/tooltips.tsx, packages/react-native/src/number-keyboard/type.ts, packages/react-native/src/number-keyboard/useNumberKeyboard.ts, packages/react-native/src/tooltip/index.md, packages/react-native/src/tooltip/index.tsx
1 NumberKeyboardFilter 和 NumberKeyboardInput 增加复制粘贴功能
=> issues 342

.github/workflows/issue-close-require.yml
=> create issue-close-require actions

.changeset/cyan-turtles-vanish.md, .umirc.ts, packages/hooks/src/useAsyncEffect/index.ts, packages/hooks/src/useTrackedEffect/index.ts, packages/lego-map/src/DrillMap/index.md
=> fix: 优化部分hooks的代码

.changeset/stale-moons-matter.md, packages/react-native/src/accordion/index.tsx, packages/react-native/src/card/index.tsx, packages/react-native/src/table/index.md, packages/react-native/src/table/index.tsx, packages/react-native/src/table/useTable.tsx, packages/react-native/src/text/index.tsx
=> fix: 修改Text默认不允许选中

.changeset/silver-mirrors-tickle.md, .changeset/swift-pants-dance.md, packages/react-native-password/src/Password.tsx, packages/react-native-password/src/PasswordModal.tsx, packages/react-native-password/src/index.md, packages/react-native-password/src/index.tsx, packages/react-native/src/form/FormListItem.tsx, packages/react-native/src/form/type.ts, packages/react-native/src/index.ts, packages/react-native/src/number-keyboard/NumberKeyboardInput.tsx, packages/react-native/src/number-keyboard/NumberKeyboardItem.tsx, packages/react-native/src/number-keyboard/NumberKeyboardModal.tsx, packages/react-native/src/number-keyboard/index.md, packages/react-native/src/number-keyboard/index.tsx, packages/react-native/src/number-keyboard/type.ts, packages/react-native/src/number-keyboard/useNumberKeyboard.ts, packages/react-native/src/number-keyboard/useNumberKeyboardModal.ts, packages/react-native/src/vehicle-keyboard/VehicleKeyboardInput.tsx, packages/react-native/src/vehicle-keyboard/VehicleKeyboardItem.tsx, packages/react-native/src/vehicle-keyboard/VehicleKeyboardModal.tsx, packages/react-native/src/vehicle-keyboard/index.md, packages/react-native/src/vehicle-keyboard/index.tsx, packages/react-native/src/vehicle-keyboard/type.ts, packages/react-native/src/vehicle-keyboard/useVehicleKeyboard.ts, packages/react-native/src/vehicle-keyboard/useVehicleKeyboardModal.ts
修改Password弹窗实现方式
FormListItem的title属性变更为label属性
=> refactor: 修改NumberKeyboard和VehicleKeyboard的弹窗实现方式
